dbus methods: listIdentity, trust
AsamK/signal-cli pull request #728
Opened 2021-09-21 08:16 UTC by johnfreed

Implement new Dbus methods:
- listIdentity(number<s>)
- trust(number<s>, safetyNumber<s>)

Update documentation

2021-09-21 21:21 UTC, AsamK requested changes

2021-09-21 21:21 UTC, AsamK commented on src/main/java/org/asamk/Signal.java
> +    List<String> listIdentity(String number) throws Error.InvalidNumber;
should rather return a struct instead of a list
And rename to `getIdentity`?

2021-09-21 21:21 UTC, AsamK commented on man/signal-cli-dbus.5.adoc
> +getGroupMembers(base64GroupId<s>) -> members<as>::
Please remove unrelated doc changes here.

2021-09-22 12:37 UTC, johnfreed commented
I took another approach to this one to more closely mirror the listIdentities command, and so I used that name.

Calling with an argument (a single contact) returns a dictionary just for that contact, with the contact number as key and the four data points as values.

Calling without an argument returns an array of dictionaries of all relevant contacts with the four data points. (Perhaps that should be instead a single dictionary with multiple keys?)

2021-09-22 17:05 UTC, johnfreed commented
I think I'll resubmit it as a single dictionary with multiple keys.

2021-09-22 17:25 UTC, johnfreed commented on man/signal-cli-dbus.5.adoc
> +getGroupMembers(base64GroupId<s>) -> members<as>::
done

2023-03-29 05:02 UTC, bublath commented
Any chance that this gets continued? A dbus interface to restore trust is the top requirement my users would still have, as they currently have to do this from commandline, instead of using my User Interface.

2023-06-05 17:27 UTC, AsamK commented
Superseded by #1259

2023-06-05 17:27 UTC, closed without merging